-- 사용자 계정 생성
-- [문법]
-- CREATE USER 계정명 IDENTIFIED BY 비밀번호;
CREATE USER C## IDENTIFIED BY 1234;
CREATE USER C##KH_JDBC IDENTIFIED BY 1234;

-- [권한 부여]
-- GRANT 권한1, 권한2, ... TO 계정명;
GRANT RESOURCE, CONNECT TO C##KH;
GRANT RESOURCE, CONNECT TO C##KH_JDBC;
ALTER USER C##KH_JDBC DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

-- [권한 해제]
-- REVOKE
REVOKE RESOURCE FROM C##KH;

-- 확인
SELECT *
FROM ROLE_SYS_PRIVS;