-- BOARD
DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;
DROP TABLE BOARD;
CREATE TABLE BOARD(
    NO                  NUMBER          PRIMARY KEY
    , TITLE             VARCHAR2(100)   NOT NULL
    , CONTENT           VARCHAR2(4000)  NOT NULL
    , ENROLL_DATE       TIMESTAMP       DEFAULT SYSDATE
);
SELECT * FROM BOARD;
INSERT INTO BOARD(NO, TITLE, CONTENT) VALUES(SEQ_BOARD_NO.NEXTVAL, '≈∏¿Ã∆≤1', 'ƒ¡≈Ÿ√˜1');
INSERT INTO BOARD(NO, TITLE, CONTENT) VALUES(SEQ_BOARD_NO.NEXTVAL, '≈∏¿Ã∆≤2', 'ƒ¡≈Ÿ√˜2');
INSERT INTO BOARD(NO, TITLE, CONTENT) VALUES(SEQ_BOARD_NO.NEXTVAL, '≈∏¿Ã∆≤3', 'ƒ¡≈Ÿ√˜3');
INSERT INTO BOARD(NO, TITLE, CONTENT) VALUES(SEQ_BOARD_NO.NEXTVAL, '≈∏¿Ã∆≤4', 'ƒ¡≈Ÿ√˜4');
INSERT INTO BOARD(NO, TITLE, CONTENT) VALUES(SEQ_BOARD_NO.NEXTVAL, '≈∏¿Ã∆≤5', 'ƒ¡≈Ÿ√˜5');
COMMIT;

-- MEMBER
DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO              NUMBER          PRIMARY KEY
    ,ID             VARCHAR2(100)   NOT NULL UNIQUE
    ,PWD            VARCHAR2(100)   NOT NULL
    ,NICK           VARCHAR2(100)   NOT NULL
    ,ENROLL_DATE    TIMESTAMP       DEFAULT SYSDATE
);



















