-- BOARD
DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;
DROP TABLE BOARD;
CREATE TABLE BOARD(
    NO                  NUMBER          PRIMARY KEY
    , TITLE             VARCHAR2(100)   NOT NULL
    , CONTENT           VARCHAR2(4000)  NOT NULL
    , ENROLL_DATE       TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN            CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
    , WRITER_NO         NUMBER          NOT NULL
);

-- MEMBER
DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO              NUMBER          PRIMARY KEY
    , ID            VARCHAR2(100)   NOT NULL UNIQUE
    , PWD           VARCHAR2(100)   NOT NULL
    , NICK          VARCHAR2(100)   NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK(DEL_YN IN ('Y','N'))
);

-- ø‹∑°≈∞
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY(WRITER_NO) REFERENCES MEMBER(NO);


SELECT * FROM BOARD;
INSERT INTO BOARD(NO, TITLE, CONTENT) VALUES(SEQ_BOARD_NO.NEXTVAL, '≈∏¿Ã∆≤1', 'ƒ¡≈Ÿ√˜1');
INSERT INTO BOARD(NO, TITLE, CONTENT) VALUES(SEQ_BOARD_NO.NEXTVAL, '≈∏¿Ã∆≤2', 'ƒ¡≈Ÿ√˜2');
INSERT INTO BOARD(NO, TITLE, CONTENT) VALUES(SEQ_BOARD_NO.NEXTVAL, '≈∏¿Ã∆≤3', 'ƒ¡≈Ÿ√˜3');
INSERT INTO BOARD(NO, TITLE, CONTENT) VALUES(SEQ_BOARD_NO.NEXTVAL, '≈∏¿Ã∆≤4', 'ƒ¡≈Ÿ√˜4');
INSERT INTO BOARD(NO, TITLE, CONTENT) VALUES(SEQ_BOARD_NO.NEXTVAL, '≈∏¿Ã∆≤5', 'ƒ¡≈Ÿ√˜5');
COMMIT;















