-- JDBC 프로젝트 과제 1번 위크플래너

-- 일정테이블
DROP TABLE DAYEVENT;
CREATE TABLE DAYEVENT(
    TITLE VARCHAR2(100)
    , DAYCAL VARCHAR2(100)
);

-- 유저테이블
DROP TABLE USERTABLE;
CREATE TABLE USERTABLE(
    ID VARCHAR2(100)
    , PWD VARCHAR2(100)
    , NICK VARCHAR2(100)
);