

-- MEMBER
DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;

DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO                  NUMBER          PRIMARY KEY
    , ID                VARCHAR2(100)   NOT NULL UNIQUE
    , PWD               VARCHAR2(100)   NOT NULL
    , NICK              VARCHAR2(100)   NOT NULL
    , PHONE             CHAR(13)        
    , EMAIL             VARCHAR2(100)
    , ADDRESS           VARCHAR2(100)
    , HOBBYS            VARCHAR2(100)
    , ENROLL_DATE       TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE       TIMESTAMP       DEFAULT SYSDATE
    , STATUS            CHAR(1)         DEFAULT 'O' CHECK (STATUS IN ('O', 'X'))
);

-- BOARD
DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;

DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD(
    NO                  NUMBER              PRIMARY KEY
    , CATEGORY_NO       NUMBER              NOT NULL
    , TITLE             VARCHAR2(100)       NOT NULL
    , CONTENT           VARCHAR2(4000)      NOT NULL
    , WRITER_NO         NUMBER              NOT NULL
    , HIT               NUMBER              DEFAULT 0
    , ENROLL_DATE       TIMESTAMP           DEFAULT SYSDATE
    , MODIFY_DATE       TIMESTAMP           DEFAULT SYSDATE
    , STATUS            CHAR(1)             DEFAULT 'O' CHECK(STATUS IN('O', 'X'))
);

-- 카테고리
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
CREATE TABLE CATEGORY(
    NO          NUMBER              PRIMARY KEY
    , NAME      VARCHAR2(100)       NOT NULL
);

-- 외래키
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY(WRITER_NO) REFERENCES MEMBER(NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY(CATEGORY_NO) REFERENCES CATEGORY(NO);

-- 데이터 INSERT (MEMBER)
INSERT INTO MEMBER (NO, ID, PWD, NICK) VALUES (0, 'admin', '1234', '관리자');
COMMIT;

-- 데이터 INSERT (CATEGORY)
INSERT INTO CATEGORY (NO, NAME) VALUES (1, '자유');
INSERT INTO CATEGORY (NO, NAME) VALUES (2, '게임');
INSERT INTO CATEGORY (NO, NAME) VALUES (3, '요리');
INSERT INTO CATEGORY (NO, NAME) VALUES (4, '운동');
INSERT INTO CATEGORY (NO, NAME) VALUES (5, '자바');
INSERT INTO CATEGORY (NO, NAME) VALUES (6, '자스');
INSERT INTO CATEGORY (NO, NAME) VALUES (7, '쿼리');
INSERT INTO CATEGORY (NO, NAME) VALUES (8, '기타');
COMMIT;

-- 데이터 INSERT (BOARD)
INSERT INTO BOARD (NO, CATEGORY_NO, TITLE, CONTENT, WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, '제목입니다111ㅎㅎㅎ', '내용입니다1', 0);
INSERT INTO BOARD (NO, CATEGORY_NO, TITLE, CONTENT, WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, 3, '제목입니다21ㅎㅎㅎ', '내용입니다2', 0);
INSERT INTO BOARD (NO, CATEGORY_NO, TITLE, CONTENT, WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, 6, '제목입니다41ㅎㅎㅎ', '내용입니다3', 0);
INSERT INTO BOARD (NO, CATEGORY_NO, TITLE, CONTENT, WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, '제목입니다111ㅎㅎㅎ', '내용입니다4', 0);
INSERT INTO BOARD (NO, CATEGORY_NO, TITLE, CONTENT, WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, 3, '제목입니다21ㅎㅎㅎ', '내용입니다5', 0);
INSERT INTO BOARD (NO, CATEGORY_NO, TITLE, CONTENT, WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, 6, '제목입니다41ㅎㅎㅎ', '내용입니다6', 0);
SELECT * FROM BOARD;
SELECT 
    B.NO
    , B.CATEGORY_NO
    , B.TITLE
    , B.CONTENT
    , B.WRITER_NO
    , B.HIT
    , B.ENROLL_DATE
    , B.MODIFY_DATE
    , B.STATUS
    , M.NICK
FROM BOARD B
JOIN MEMBER M ON M.NO = B.WRITER_NO
WHERE B.STATUS = 'O' 
ORDER BY B.NO DESC;
SELECT B.NO , B.CATEGORY_NO , B.TITLE , B.CONTENT , B.WRITER_NO , B.HIT , B.ENROLL_DATE , B.MODIFY_DATE , B.STATUS , M.NICK FROM BOARD B JOIN MEMBER M ON M.NO = B.WRITER_NO WHERE B.STATUS = 'O' ORDER BY B.NO DESC;




















