

-- MEMBER
DROP SEQUENCE SEQ_MEMBER_NO;
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE NOCYCLE;

DROP TABLE MEMBER CASCADE CONSTRAINTS;
CREATE TABLE MEMBER(
    NO                  NUMBER          PRIMARY KEY
    , ID                VARCHAR2(100)   NOT NULL UNIQUE
    , PWD               VARCHAR2(100)   NOT NULL
    , NICK              VARCHAR2(100)   NOT NULL
    , PHONE             CHAR(13)        
    , EMAIL             VARCHAR2(100)
    , ADDRESS           VARCHAR2(100)
    , HOBBYS            VARCHAR2(100)
    , ENROLL_DATE       TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE       TIMESTAMP       DEFAULT SYSDATE
    , STATUS            CHAR(1)         DEFAULT 'O' CHECK (STATUS IN ('O', 'X'))
);

-- BOARD
DROP SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE NOCYCLE;

DROP TABLE BOARD CASCADE CONSTRAINTS;
CREATE TABLE BOARD(
    NO                  NUMBER              PRIMARY KEY
    , CATEGORY_NO       NUMBER              NOT NULL
    , TITLE             VARCHAR2(100)       NOT NULL
    , CONTENT           VARCHAR2(4000)      NOT NULL
    , WRITER_NO         NUMBER              NOT NULL
    , HIT               NUMBER              DEFAULT 0
    , ENROLL_DATE       TIMESTAMP           DEFAULT SYSDATE
    , MODIFY_DATE       TIMESTAMP           DEFAULT SYSDATE
    , STATUS            CHAR(1)             DEFAULT 'O' CHECK(STATUS IN('O', 'X'))
);

-- GALLERY
DROP SEQUENCE SEQ_GALLERY_NO;
CREATE SEQUENCE SEQ_GALLERY_NO NOCACHE NOCYCLE;

DROP TABLE GALLERY CASCADE CONSTRAINTS;
CREATE TABLE GALLERY(
    NO                  NUMBER              PRIMARY KEY
    , TITLE             VARCHAR2(100)       NOT NULL
    , WRITER_NO         NUMBER              NOT NULL
    , HIT               NUMBER              DEFAULT 0
    , ENROLL_DATE       TIMESTAMP           DEFAULT SYSDATE
    , MODIFY_DATE       TIMESTAMP           DEFAULT SYSDATE
    , STATUS            CHAR(1)             DEFAULT 'O' CHECK(STATUS IN('O', 'X'))
);

-- ATTACHMENT
DROP SEQUENCE SEQ_ATTACHMENT_NO;
CREATE SEQUENCE SEQ_ATTACHMENT_NO NOCACHE NOCYCLE;

DROP TABLE ATTACHMENT CASCADE CONSTRAINTS;
CREATE TABLE ATTACHMENT(
    NO                  NUMBER              PRIMARY KEY
    , REF_NO            NUMBER              NOT NULL
    , ORIGIN_NAME       VARCHAR2(1000)     
    , CHANGE_NAME       VARCHAR2(1000)      NOT NULL
    , FILE_PATH         VARCHAR2(1000)      NOT NULL
    , THUMBNAIL_YN      CHAR(1)             DEFAULT 'N' CHECK(THUMBNAIL_YN IN ('Y', 'N'))
);

-- 카테고리
DROP TABLE CATEGORY CASCADE CONSTRAINTS;
CREATE TABLE CATEGORY(
    NO          NUMBER              PRIMARY KEY
    , NAME      VARCHAR2(100)       NOT NULL
);

-- COMMENT
DROP SEQUENCE SEQ_REPLY_NO;
CREATE SEQUENCE SEQ_REPLY_NO NOCACHE NOCYCLE;
DROP TABLE REPLY CASCADE CONSTRAINTS;
CREATE TABLE REPLY(
    NO              NUMBER          PRIMARY KEY
    , REF_NO        NUMBER          NOT NULL
    , CONTENT       VARCHAR2(1000)  NOT NULL
    , WRITER_NO     NUMBER          NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , STATUS        CHAR(1)         DEFAULT 'O' CHECK( STATUS IN ('O','X') )
);

-- 외래키
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_MEMBER FOREIGN KEY(WRITER_NO) REFERENCES MEMBER(NO);
ALTER TABLE BOARD ADD CONSTRAINT FK_BOARD_CATEGORY FOREIGN KEY(CATEGORY_NO) REFERENCES CATEGORY(NO);
ALTER TABLE ATTACHMENT ADD CONSTRAINT FK_ATTACHMENT_REF_NO FOREIGN KEY(REF_NO) REFERENCES GALLERY(NO);
ALTER TABLE REPLY ADD CONSTRAINT FK_REPLY_REF_NO FOREIGN KEY(REF_NO) REFERENCES BOARD(NO);

-- 데이터 INSERT (MEMBER)
INSERT INTO MEMBER (NO, ID, PWD, NICK) VALUES (0, 'admin', '1234', '관리자');
COMMIT;

-- 데이터 INSERT (CATEGORY)
INSERT INTO CATEGORY (NO, NAME) VALUES (1, '자유');
INSERT INTO CATEGORY (NO, NAME) VALUES (2, '게임');
INSERT INTO CATEGORY (NO, NAME) VALUES (3, '요리');
INSERT INTO CATEGORY (NO, NAME) VALUES (4, '운동');
INSERT INTO CATEGORY (NO, NAME) VALUES (5, '자바');
INSERT INTO CATEGORY (NO, NAME) VALUES (6, '자스');
INSERT INTO CATEGORY (NO, NAME) VALUES (7, '쿼리');
INSERT INTO CATEGORY (NO, NAME) VALUES (8, '기타');
COMMIT;

-- 데이터 INSERT (BOARD)
INSERT INTO BOARD (NO, CATEGORY_NO, TITLE, CONTENT, WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, '제목입니다111ㅎㅎㅎ', '내용입니다1', 0);
INSERT INTO BOARD (NO, CATEGORY_NO, TITLE, CONTENT, WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, 3, '제목입니다21ㅎㅎㅎ', '내용입니다2', 0);
INSERT INTO BOARD (NO, CATEGORY_NO, TITLE, CONTENT, WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, 6, '제목입니다41ㅎㅎㅎ', '내용입니다3', 0);
INSERT INTO BOARD (NO, CATEGORY_NO, TITLE, CONTENT, WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, 1, '제목입니다111ㅎㅎㅎ', '내용입니다4', 0);
INSERT INTO BOARD (NO, CATEGORY_NO, TITLE, CONTENT, WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, 3, '제목입니다21ㅎㅎㅎ', '내용입니다5', 0);
INSERT INTO BOARD (NO, CATEGORY_NO, TITLE, CONTENT, WRITER_NO) VALUES (SEQ_BOARD_NO.NEXTVAL, 6, '제목입니다41ㅎㅎㅎ', '내용입니다6', 0);

-- 데이터 INSERT (GALLERY)
-- 데이터 (GALLERY)
INSERT INTO GALLERY ( NO ,TITLE ,WRITER_NO ) VALUES ( SEQ_GALLERY_NO.NEXTVAL , '갤러리제목01' , 0 );
INSERT INTO GALLERY ( NO ,TITLE ,WRITER_NO ) VALUES ( SEQ_GALLERY_NO.NEXTVAL , '갤러리제목02' , 0 );
INSERT INTO GALLERY ( NO ,TITLE ,WRITER_NO ) VALUES ( SEQ_GALLERY_NO.NEXTVAL , '갤러리제목03' , 0 );
INSERT INTO GALLERY ( NO ,TITLE ,WRITER_NO ) VALUES ( SEQ_GALLERY_NO.NEXTVAL , '갤러리제목04' , 0 );
INSERT INTO GALLERY ( NO ,TITLE ,WRITER_NO ) VALUES ( SEQ_GALLERY_NO.NEXTVAL , '갤러리제목05' , 0 );
INSERT INTO GALLERY ( NO ,TITLE ,WRITER_NO ) VALUES ( SEQ_GALLERY_NO.NEXTVAL , '갤러리제목06' , 0 );
COMMIT;

-- 데이터 INSERT (ATTACHMENT)
INSERT INTO ATTACHMENT ( NO ,REF_NO ,ORIGIN_NAME ,CHANGE_NAME ,FILE_PATH, THUMBNAIL_YN ) VALUES ( SEQ_ATTACHMENT_NO.NEXTVAL , 1 , '첨부파일1.PNG' , '실제저장된파일명' , '파일경로', 'Y');
INSERT INTO ATTACHMENT ( NO ,REF_NO ,ORIGIN_NAME ,CHANGE_NAME ,FILE_PATH, THUMBNAIL_YN ) VALUES ( SEQ_ATTACHMENT_NO.NEXTVAL , 1 , '첨부파일2.PNG' , '실제저장된파일명' , '파일경로', 'N');
INSERT INTO ATTACHMENT ( NO ,REF_NO ,ORIGIN_NAME ,CHANGE_NAME ,FILE_PATH, THUMBNAIL_YN ) VALUES ( SEQ_ATTACHMENT_NO.NEXTVAL , 2 , '첨부파일3.PNG' , '실제저장된파일명' , '파일경로', 'Y');
INSERT INTO ATTACHMENT ( NO ,REF_NO ,ORIGIN_NAME ,CHANGE_NAME ,FILE_PATH, THUMBNAIL_YN ) VALUES ( SEQ_ATTACHMENT_NO.NEXTVAL , 2 , '첨부파일4.PNG' , '실제저장된파일명' , '파일경로', 'N');
INSERT INTO ATTACHMENT ( NO ,REF_NO ,ORIGIN_NAME ,CHANGE_NAME ,FILE_PATH, THUMBNAIL_YN ) VALUES ( SEQ_ATTACHMENT_NO.NEXTVAL , 3 , '첨부파일5.PNG' , '실제저장된파일명' , '파일경로', 'Y');
INSERT INTO ATTACHMENT ( NO ,REF_NO ,ORIGIN_NAME ,CHANGE_NAME ,FILE_PATH, THUMBNAIL_YN ) VALUES ( SEQ_ATTACHMENT_NO.NEXTVAL , 3 , '첨부파일6.PNG' , '실제저장된파일명' , '파일경로', 'N');
INSERT INTO ATTACHMENT ( NO ,REF_NO ,ORIGIN_NAME ,CHANGE_NAME ,FILE_PATH, THUMBNAIL_YN ) VALUES ( SEQ_ATTACHMENT_NO.NEXTVAL , 4 , '첨부파일7.PNG' , '실제저장된파일명' , '파일경로', 'Y');
INSERT INTO ATTACHMENT ( NO ,REF_NO ,ORIGIN_NAME ,CHANGE_NAME ,FILE_PATH, THUMBNAIL_YN ) VALUES ( SEQ_ATTACHMENT_NO.NEXTVAL , 4 , '첨부파일8.PNG' , '실제저장된파일명' , '파일경로', 'N');
INSERT INTO ATTACHMENT ( NO ,REF_NO ,ORIGIN_NAME ,CHANGE_NAME ,FILE_PATH, THUMBNAIL_YN ) VALUES ( SEQ_ATTACHMENT_NO.NEXTVAL , 5 , '첨부파일9.PNG' , '실제저장된파일명' , '파일경로', 'Y');
INSERT INTO ATTACHMENT ( NO ,REF_NO ,ORIGIN_NAME ,CHANGE_NAME ,FILE_PATH, THUMBNAIL_YN ) VALUES ( SEQ_ATTACHMENT_NO.NEXTVAL , 5 , '첨부파일10.PNG' , '실제저장된파일명' , '파일경로', 'N');
INSERT INTO ATTACHMENT ( NO ,REF_NO ,ORIGIN_NAME ,CHANGE_NAME ,FILE_PATH, THUMBNAIL_YN ) VALUES ( SEQ_ATTACHMENT_NO.NEXTVAL , 6 , '첨부파일11.PNG' , '실제저장된파일명' , '파일경로', 'Y');
INSERT INTO ATTACHMENT ( NO ,REF_NO ,ORIGIN_NAME ,CHANGE_NAME ,FILE_PATH, THUMBNAIL_YN ) VALUES ( SEQ_ATTACHMENT_NO.NEXTVAL , 6 , '첨부파일12.PNG' , '실제저장된파일명' , '파일경로', 'N');
COMMIT;

-- 데이터 (REPLY)
INSERT INTO REPLY(NO, REF_NO, CONTENT, WRITER_NO) VALUES(SEQ_REPLY_NO.NEXTVAL, 1, '댓글내용ㅋㅋㅋ1', 0);
INSERT INTO REPLY(NO, REF_NO, CONTENT, WRITER_NO) VALUES(SEQ_REPLY_NO.NEXTVAL, 1, '댓글내용ㅋㅋㅋ2', 0);
INSERT INTO REPLY(NO, REF_NO, CONTENT, WRITER_NO) VALUES(SEQ_REPLY_NO.NEXTVAL, 1, '댓글내용ㅋㅋㅋ3', 0);
INSERT INTO REPLY(NO, REF_NO, CONTENT, WRITER_NO) VALUES(SEQ_REPLY_NO.NEXTVAL, 1, '댓글내용ㅋㅋㅋ4', 0);
INSERT INTO REPLY(NO, REF_NO, CONTENT, WRITER_NO) VALUES(SEQ_REPLY_NO.NEXTVAL, 1, '댓글내용ㅋㅋㅋ5', 0);
COMMIT;


--SELECT * FROM BOARD;
SELECT 
    B.NO
    , B.CATEGORY_NO
    , B.TITLE
    , B.CONTENT
    , B.WRITER_NO
    , B.HIT
    , B.ENROLL_DATE
    , B.MODIFY_DATE
    , B.STATUS
    , M.NICK
FROM BOARD B
JOIN MEMBER M ON M.NO = B.WRITER_NO
WHERE B.STATUS = 'O' 
ORDER BY B.NO DESC;
SELECT B.NO , B.CATEGORY_NO , B.TITLE , B.CONTENT , B.WRITER_NO , B.HIT , B.ENROLL_DATE , B.MODIFY_DATE , B.STATUS , M.NICK FROM BOARD B JOIN MEMBER M ON M.NO = B.WRITER_NO WHERE B.STATUS = 'O' ORDER BY B.NO DESC;

SELECT 
    G.NO AS GALLERY_NO
    , G.TITLE
    , G.WRITER_NO
    , G.HIT
    , G.ENROLL_DATE
    , G.MODIFY_DATE
    , G.STATUS
    , A.NO AS ATTACHMENT_NO
    , A.REF_NO
    , A.ORIGIN_NAME
    , A.CHANGE_NAME
    , A.FILE_PATH
    , M.NICK AS WRITER_NICK
FROM GALLERY G
JOIN MEMBER M ON G.WRITER_NO = M.NO
JOIN ATTACHMENT A ON G.NO = A.REF_NO
WHERE G.STATUS = 'O'
ORDER BY G.NO DESC;

-- 댓글 목록 조회
SELECT 
    NO
    ,REF_NO
    ,CONTENT
    ,WRITER_NO
    ,ENROLL_DATE
    ,STATUS
FROM REPLY
WHERE REF_NO = 1
AND STATUS = 'O'
ORDER BY NO DESC
;

-- 댓글 작성
INSERT INTO REPLY
(
    NO
    ,REF_NO
    ,CONTENT
    ,WRITER_NO
)
VALUES
(
    SEQ_REPLY_NO.NEXTVAL
    , 게시글번호
    , 내용
    , 작성자번호
)
;















