-- 마이바티스 수업용 테이블
DROP TABLE BOARD_TEMP CASCADE CONSTRAINTS;
CREATE TABLE BOARD_TEMP(
    TITLE               VARCHAR2(1000)
    , CONTENT           VARCHAR2(4000)
    , ENROLL_DATE       TIMESTAMP DEFAULT SYSDATE
);

INSERT INTO BOARD_TEMP (TITLE, CONTENT) VALUES ('디로디로디로', '내용입니다.');
SELECT * FROM BOARD_TEMP;
ROLLBACK;