-- 계정만들기
CREATE USER C##KH IDENTIFIED BY 1234;
-- 권한 부여
GRANT CONNECT, RESOURCE TO C##KH;
-- 테이블스페이스 권한 부여
ALTER USER C##KH DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

/*
-- 조회
CREATE TABLE MEMBER(
    ID VARCHAR2(100),
    PWD VARCHAR2(100)
);

-- 조회
SELECT * FROM MEMBER;
SELECT * FROM MEMBER WHERE ID = 'abc';
SELECT PWD FROM MEMBER WHERE ID = 'abc'; -- 칼럼조회

-- 추가(인설트)
INSERT INTO MEMBER (ID, PWD) VALUES ('USER01', 'QLALFQJSGH');
INSERT INTO MEMBER (ID, PWD) VALUES ('USER02', 'QLALFQJSGH');
INSERT INTO MEMBER (ID, PWD) VALUES ('USER03', 'QLALFQJSGH');
INSERT INTO MEMBER (ID, PWD) VALUES ('USER04', 'QLALFQJSGH');
INSERT INTO MEMBER (ID, PWD) VALUES ('USER05', 'QLALFQJSGH');
INSERT INTO MEMBER (ID, PWD) VALUES ('USER06', '1111');
INSERT INTO MEMBER (ID, PWD) VALUES ('USER07', '2222');
INSERT INTO MEMBER (ID, PWD) VALUES ('USER08', '3333');
INSERT INTO MEMBER (ID, PWD) VALUES ('USER09', '4444');
INSERT INTO MEMBER (ID, PWD) VALUES ('USER10', '5555');
INSERT INTO MEMBER (ID, PWD) VALUES ('abc', '0000');

-- 삭제
DELETE FROM MEMBER WHERE ID = 'abc';
DELETE FROM MEMBER WHERE PWD = 'QLALFQJSGH';
DELETE FROM MEMBER; -- 행 전체 삭제

-- 테이블 삭제
DROP TABLE MEMBER;
*/